language: node_js
node_js:
  - "stable"
cache: npm

install:
  - npm ci
  
script:
  - CI='' npm run build
 
deploy:
  provider: heroku
  api_key:
    secure: fe661b4b-d01b-4a6f-997c-6352c6f25bc9
  app: ecommerce-react-unsaac1
  skip-cleanup: true
