language: node_js
node_js:
  - "stable"
cache: npm

install:
  - npm ci
  
script:
  - CI='' npm run build
 
deploy:
  provider: heroku
  api_key:
    secure: dae865e5-fb31-46ec-8bf6-d9550ca32177
  app: e-commerce-uwunsaac
  skip-cleanup: true
